version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/circuits"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "zeroize"
      - dependency-name: "zeroize_derive"
      - dependency-name: "rayon"
      - dependency-name: "rayon-core"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"