//! In-memory relay state.
//!
//! Phase 0, honestly: everything here lives in a `Mutex` and evaporates on
//! restart. `docs/ARCHITECTURE.md` describes the relay as "public,
//! stateless (or minimally stateful)" — this is the minimally-stateful
//! reference implementation of that idea, not a production storage layer.
//! A real deployment needs to persist `seen_nullifiers` at minimum (replay
//! protection must survive a restart), which `reputation_accumulator`'s
//! `accumulate` already supports via its threaded-in `seen_nullifiers` set
//! — swapping in real persistence here is a storage-layer change, not a
//! protocol change.

use ark_bn254::Bn254;
use ark_groth16::VerifyingKey;
use reputation_accumulator::TierWeights;
use std::collections::{HashMap, HashSet};
use std::sync::Mutex;

#[derive(Default)]
pub struct Inner {
    pub seen_nullifiers: HashSet<String>,
    pub scores: HashMap<(String, u64), u32>,
    pub proof_counts: HashMap<(String, u64), u32>,
    /// indicator_hash (hex) -> raw indicator string, recorded only when a
    /// submission both verified AND included a disclosure whose hash
    /// matched the proof's indicator_hash — see `submit_observation` in
    /// lib.rs. Indicators never disclosed this way simply never appear
    /// here, which is exactly what STIX export needs: no entry, no STIX
    /// object, per `schema/stix_mapping.md`'s "Explicit non-mapping".
    pub disclosed_indicators: HashMap<String, String>,
}

pub struct AppState {
    /// The Groth16 verifying key every submitted proof is checked against.
    /// Phase 0: generated by `umbra-relay-keygen` from a local
    /// (non-ceremony) setup — see that binary's own warning banner and
    /// docs/THREAT_MODEL.md's "Trusted setup" section. Do not treat proofs
    /// verified against this key as sound against a party who could have
    /// retained the toxic waste from that local setup.
    pub vk: VerifyingKey<Bn254>,
    pub weights: TierWeights,
    /// Hex-encoded credential-tree roots this relay treats as belonging to
    /// a real, vetted issuer. A submission's claimed `min_tier` is only
    /// trusted for scoring weight when its `credential_root` is in this
    /// set — see `submit_observation` in lib.rs for why. Empty by default:
    /// Phase 0 has no real issuer yet, so nothing is trusted and every
    /// observation scores as tier 0 regardless of its (cryptographically
    /// valid) tier claim.
    pub trusted_credential_roots: HashSet<String>,
    /// Raw score that maps to STIX `confidence: 100` — see
    /// `stix::normalize_confidence`. Defaults to 10 (tier-0 weight 1, so
    /// ~10 independent tier-0 contributors — or fewer higher-tier ones —
    /// reach full confidence); tune per deployment.
    pub score_for_full_confidence: u32,
    /// Identifies this relay in exported STIX objects'
    /// `x_umbra_relay_id`, so a consumer cross-checking multiple relays
    /// knows which one produced a given assertion.
    pub relay_id: String,
    pub inner: Mutex<Inner>,
}

impl AppState {
    pub fn new(vk: VerifyingKey<Bn254>, weights: TierWeights) -> Self {
        Self {
            vk,
            weights,
            trusted_credential_roots: HashSet::new(),
            score_for_full_confidence: 10,
            relay_id: "umbra-relay-dev".to_string(),
            inner: Mutex::new(Inner::default()),
        }
    }

    /// Builder-style setter, since trusted issuer roots are an optional,
    /// Phase-0-typically-empty piece of relay configuration rather than
    /// something every caller of `new` needs to think about.
    pub fn with_trusted_credential_roots(mut self, roots: HashSet<String>) -> Self {
        self.trusted_credential_roots = roots;
        self
    }

    pub fn with_score_for_full_confidence(mut self, score: u32) -> Self {
        self.score_for_full_confidence = score;
        self
    }

    pub fn with_relay_id(mut self, relay_id: String) -> Self {
        self.relay_id = relay_id;
        self
    }
}
