//! In-memory relay state.
//!
//! Phase 0, honestly: everything here lives in a `Mutex` and evaporates on
//! restart. `docs/ARCHITECTURE.md` describes the relay as "public,
//! stateless (or minimally stateful)" — this is the minimally-stateful
//! reference implementation of that idea, not a production storage layer.
//! A real deployment needs to persist `seen_nullifiers` at minimum (replay
//! protection must survive a restart), which `reputation_accumulator`'s
//! `accumulate` already supports via its threaded-in `seen_nullifiers` set
//! — swapping in real persistence here is a storage-layer change, not a
//! protocol change.

use ark_bn254::Bn254;
use ark_groth16::VerifyingKey;
use reputation_accumulator::TierWeights;
use std::collections::{HashMap, HashSet};
use std::sync::Mutex;

#[derive(Default)]
pub struct Inner {
    pub seen_nullifiers: HashSet<String>,
    pub scores: HashMap<(String, u64), u32>,
    pub proof_counts: HashMap<(String, u64), u32>,
}

pub struct AppState {
    /// The Groth16 verifying key every submitted proof is checked against.
    /// Phase 0: generated by `umbra-relay-keygen` from a local
    /// (non-ceremony) setup — see that binary's own warning banner and
    /// docs/THREAT_MODEL.md's "Trusted setup" section. Do not treat proofs
    /// verified against this key as sound against a party who could have
    /// retained the toxic waste from that local setup.
    pub vk: VerifyingKey<Bn254>,
    pub weights: TierWeights,
    /// Hex-encoded credential-tree roots this relay treats as belonging to
    /// a real, vetted issuer. A submission's claimed `min_tier` is only
    /// trusted for scoring weight when its `credential_root` is in this
    /// set — see `submit_observation` in lib.rs for why. Empty by default:
    /// Phase 0 has no real issuer yet, so nothing is trusted and every
    /// observation scores as tier 0 regardless of its (cryptographically
    /// valid) tier claim.
    pub trusted_credential_roots: HashSet<String>,
    pub inner: Mutex<Inner>,
}

impl AppState {
    pub fn new(vk: VerifyingKey<Bn254>, weights: TierWeights) -> Self {
        Self {
            vk,
            weights,
            trusted_credential_roots: HashSet::new(),
            inner: Mutex::new(Inner::default()),
        }
    }

    /// Builder-style setter, since trusted issuer roots are an optional,
    /// Phase-0-typically-empty piece of relay configuration rather than
    /// something every caller of `new` needs to think about.
    pub fn with_trusted_credential_roots(mut self, roots: HashSet<String>) -> Self {
        self.trusted_credential_roots = roots;
        self
    }
}
